services:  
  postgres:
    image: postgres:18
    container_name: postgres-casino
    restart: always
    environment:
      POSTGRES_DB: casino
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    volumes:
      - casino_pgdata:/var/lib/postgresql

  casino-bot:
    build:
      context: .
      dockerfile: docker_conf/casino-dockerfile
    container_name: casino-bot
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      CASINO_TOKEN: ${CASINO_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWD: ${POSTGRES_PASSWD}
      DISCORD_WEBHOOK_ALERT: ${DISCORD_WEBHOOK_ALERT}
      MY_DISCORD_UID: ${MY_DISCORD_UID}

volumes:
  casino_pgdata:

