FROM python:3.11-slim

WORKDIR /app

# Install nano and system dependencies
RUN apt-get update && \
    apt-get install -y nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY slots.py .
COPY fundamentals.py .
COPY blackjack.py .
COPY wheel_of_fortune.py .

CMD ["python", "main.py"]
