# Creates PR on push to main
name: Create Draft PR

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2

      - name: Authenticate GitHub CLI using PAT
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          echo "$MY_PAT" | gh auth login --with-token

      - name: Check for existing PR
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
          BRANCH_NAME: ${{ github.ref_name }}
          REPO_NAME: ${{ github.repository }}
        run: |
          existing_pr=$(gh pr list --repo "$REPO_NAME" --head "$BRANCH_NAME" --state open --json number --jq '.[].number')
          if [ -n "$existing_pr" ]; then
            echo "A PR already exists for branch $BRANCH_NAME (#$existing_pr). Skipping creation."
            exit 0
          fi
          echo "No existing PR found for branch $BRANCH_NAME. Proceeding..."

      - name: Create Draft Pull Request
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
          BRANCH_NAME: ${{ github.ref_name }}
          REPO_NAME: ${{ github.repository }}
        run: |
          gh pr create --repo "$REPO_NAME" \
                       --base main \
                       --head "$BRANCH_NAME" \
                       --title "Draft PR for $BRANCH_NAME" \
                       --body "Automatically created draft PR." \
                       --draft
